apiVersion: apps/v1
kind: Deployment
metadata:
  name: stg-coworking-platform-be
  namespace: stg
  labels:
    app: stg-coworking-platform-be
    environment: stg
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: stg-coworking-platform-be
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: stg-coworking-platform-be
        environment: stg
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: stg-coworking-platform-be
          image: 344367180480.dkr.ecr.ap-south-1.amazonaws.com/coworking-platform-be:b2befe7
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: coworking-platform-be-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
