apiVersion: apps/v1
kind: Deployment
metadata:
  name: stg-admin-lawyered-fe
  namespace: stg
  labels:
    app: stg-admin-lawyered-fe
    environment: stg
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: stg-admin-lawyered-fe
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: stg-admin-lawyered-fe
        environment: stg
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: stg-admin-lawyered-fe
          image: 344367180480.dkr.ecr.ap-south-1.amazonaws.com/admin-lawyered-fe:4d8629d
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: admin-lawyered-fe-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"

