apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-redis
  namespace: argo-cd
  labels:
    app: stg-redis
    tier: infrastructure
    environment: stg
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: "25.4.1"
      helm:
        releaseName: stg-redis
        valueFiles:
          - $values/deployments/stg-redis/values.yaml
    - repoURL: git@github.com:Lawyered-in/k8s-manifest.git
      targetRevision: staging
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 3
