apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-coworking-platform-fe
  namespace: argo-cd
  labels:
    app: stg-coworking-platform-fe
    tier: application
    environment: stg
spec:
  project: default
  source:
    repoURL: git@github.com:Lawyered-in/k8s-manifest.git
    targetRevision: staging
    path: deployments/stg-coworking-platform-fe
  destination:
    server: https://kubernetes.default.svc
    namespace: stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Replace=true
  revisionHistoryLimit: 3
