apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stg-finvica-ingress
  namespace: stg
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:344367180480:certificate/2dfdb25d-1a08-427b-82f8-b45f94ab4fd1
    alb.ingress.kubernetes.io/group.name: laweryerd-np-group
    alb.ingress.kubernetes.io/group.order: "50"
    alb.ingress.kubernetes.io/success-codes: "200,301,302,404"
    alb.ingress.kubernetes.io/load-balancer-name: lawyered-ingress-alb
spec:
  rules:

  # ── staging.finvica.com → prosper frontend ─────────────────────────────────
  - host: staging.finvica.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: stg-prosper-fe
              port:
                number: 80

  # ── staging-api.finvica.com → prosper backend ──────────────────────────────
  - host: staging-api.finvica.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: stg-prosper-be
              port:
                number: 80

  # ── staging-faas.finvica.com → faas frontend ───────────────────────────────
  - host: staging-faas.finvica.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: stg-faas-fe
              port:
                number: 80

  # ── staging-faas-api.finvica.com → faas backend ────────────────────────────
  - host: staging-faas-api.finvica.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: stg-faas-be
              port:
                number: 80
