apiVersion: v1
kind: Service
metadata:
  name: stg-coworking-platform-fe
  namespace: stg
  labels:
    app: stg-coworking-platform-fe
    environment: stg
spec:
  type: ClusterIP
  selector:
    app: stg-coworking-platform-fe
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
