apiVersion: apps/v1
kind: Deployment
metadata:
  name: stg-finvica-web
  namespace: stg
  labels:
    app: stg-finvica-web
    environment: stg
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: stg-finvica-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: stg-finvica-web
        environment: stg
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: stg-finvica-web
          image: 344367180480.dkr.ecr.ap-south-1.amazonaws.com/finvica-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: finvica-web-secret
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
