apiVersion: v1
kind: Service
metadata:
  name: stg-lawyered-be
  namespace: stg
  labels:
    app: stg-lawyered-be
    environment: stg
spec:
  type: ClusterIP
  selector:
    app: stg-lawyered-be
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
