apiVersion: v1
kind: Service
metadata:
  name: stg-challan-screening
  namespace: stg
  labels:
    app: stg-challan-screening
    environment: stg
spec:
  type: ClusterIP
  selector:
    app: stg-challan-screening
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
