apiVersion: v1
kind: Service
metadata:
  name: stg-partners-portal-fe-feature
  namespace: stg
  labels:
    app: stg-partners-portal-fe-feature
    environment: stg
spec:
  type: ClusterIP
  selector:
    app: stg-partners-portal-fe-feature
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
