apiVersion: batch/v1
kind: Job
metadata:
  name: faas-be-migrate-latest
  namespace: stg
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-options: ServerSideApply=false
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-migrate
          image: 344367180480.dkr.ecr.ap-south-1.amazonaws.com/faas-be:latest
          command: ["npm", "run", "db:migrate"]
          envFrom:
            - secretRef:
                name: faas-be-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
